version: "3.9"
services:
  app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/jwtappdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: jwtappdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
#  Caching → user’ın todolarını cache’e koy (örneğin Hazelcast/Redis).