#spring.application.name=Auth_JWT_App
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 172503
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update   # ilk a?amada tabloyu otomatik olu?turur
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema : jwtappdb


server:
  port: 8080

jwt:
  secret: MyVeryLongAndSecureJwtSecretKey_ChangeThisToEnvVar_2025  # daha sonra JwtService?de kullanaca??z
  expiration: 900000  # 15 dakika (milisaniye)

